### ISSUE TITLE
How to plot results

### ISSUE THREAD

**Issue by ChiaCheng-Tsai** [GoldFeniks/Ample#3]
Dear Andrey,

I have compiled the Acoustic well. Many thanks for your innovation. Wish I can have contribution very soon. 

By the way, I will be more than happy if you can give me some hint about how to plot results of Acoustic.

Take canyon for example, I got 150.txt (two columns) and meta.json as
{
"binary": false,
"dimensions": [
[
4
],
{
"bounds": {
"a": 0.0,
"b": 10000.0,
"d": 100.0
},
"n": 101
},
{
"bounds": {
"a": -3000.0,
"b": 3000.0,
"d": 1.0
},
"n": 6001
},
{
"bounds": {
"a": 10.0,
"b": 10.0,

It is supposed that I may miss something which I will figure out as soon as possible

Thanks again

Finite Tsai

**Comment by GoldFeniks** [comment]
The output is multidimensional, so the dimensions are specified in JSON format as an array of some sort of objects. I assume this is a WAMPE solution output. So the first value `[ 4 ]` is the number of acoustic modes and can be ignored for now, because you only want to plot the result (also I will probably completely move it to somewhere else, right now this is for sort of debugging). The next dimension is `x`, so
```json
{
    "bounds": {
        "a": 0,
        "b": 10000
    },
    "n": 101
}
```
means that there're 101 points over `x` dimension uniformly distributed from `0` to `10000`. Similarly the next dimension is `y`, so it's `6001` points from `-3000` to `3000`. The last dimension is `z`, it's supposed to be one point `10`. All this means that the file contains `101 * 6001 * 1` values. Since output is complex each value is represented by two real values: real and imaginary part. I would suggest to read all data as complex values and then reshape it to `(101, 6001)`. Such array should be easy to plot using something like Mathematica
